name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python: [ '3.6', '3.7' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - run: python -m pip install --upgrade pip
    - run: pip install flake8 coverage
    - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - run: coverage run -m unittest discover
    - run: coverage xml
    - if: matrix.os == 'ubuntu-latest' && matrix.python == '3.7'
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_SCANNER_OPTS: -Dsonar.sourceEncoding=UTF-8 -Dsonar.python.coverage.reportPaths=coverage.xml -Dsonar.organization=albertus82-github -Dsonar.projectKey=it.albertus:jar-classes-version-detector
